### ISSUE TITLE
Add "es" locale

### ISSUE THREAD

**Issue by rap2hpoutre** [rap2hpoutre/remove-stop-words#2]

**Comment by elminson** [comment]
Check the PR please :)

**Comment by elminson** [comment]
What about add conversion from uppercases, lowercase, uppercases first letters of each words cases?

**Comment by rap2hpoutre** [comment]
See: https://github.com/rap2hpoutre/remove-stop-words/pull/4

**Comment by rap2hpoutre** [comment]
Thank you!

> What about add conversion from uppercases, lowercase, uppercases first letters of each words cases?

It already works for both uppercase and lower case, thanks to this line:

https://github.com/rap2hpoutre/remove-stop-words/blob/05efb559e349da5314bab061a1a1d22e9eec7030/src/remove_stop_words.php#L8

**Comment by rap2hpoutre** [comment]
Fixed via #4
